### PR TITLE
Support for `empty` and `notEmpty` operators.

### PR DESCRIPTION
**Pull request by leftclickben**
+ Add `valueType` parameter in `Condition` to determine whether
  the field should be displayed.
+ Use `valueTypeIs` function to toggle display fo `value` field.
+ Add templates in `searchService` for new operators.
+ Remove `filter` call in `searchService`; this was causing empty
  values to be omitted, which caused an inconsistent result on
  browser page reload.

### CODE REVIEW

**Comment by leftclickben** [comment]
It works if you have something else as well. Let's merge and raise an issue later to fix this.

**Comment by kehh** [comment]
Didn't see this till we were in the car.  I merged the rest and deployed to staging and UAT.

**Comment by kehh** [comment]
Plus there are now conflicts

**Comment by leftclickben** [comment]
I'm going to merge this so that we can all move on, but for the record:

@kehh it now allows a query to consist of only an `empty` / `notEmpty` comparison and permits submission of the form.  It also only displays the completely specified parts of the query in the query display.  

@mostro20 this fixes the UX issue (unrelated to this PR but I'm being pragmatic since it is such a minor change) that you raised in #90.  The whole sentence is now a link to the specific search in the shop, no link to the shop home page required as you commented.

**Comment by leftclickben** [comment]
@kehh For the record, the thing that was causing the issues was actually the fact that the `BasicSearchComponent` was still active when the `QueryBuilderComponent` was enabled.  In fact, by switching between the modes several times, you could have several of each, all with their own subscriptions to the query `observable`.  Part of this final change was to `dispose` of the subscriptions when the component itself is `dispose`d, which prevents memory issues as well as fixing the button enabled-ness issue.

**Pull request merged**
